version: '3.9'

services:
  roach-single:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    environment:
      COCKROACH_DATABASE: ${DATABASE_NAME}
      COCKROACH_USER: ${USER_NAME}
      COCKROACH_PASSWORD: ${PASSWORD}
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - roach-single:/cockroach/cockroach-data
      - ~/init-scripts:/docker-entrypoint-initdb.d

volumes:
  roach-single: