version: '3.9'

services:
  roach-single:
    image: cockroachdb/cockroach:latest
    # cockroachdb 啟動後, 只跑單一 Node, --insecure(不走 cert 憑證連線)
    command: start-single-node --insecure

    # 參照 .env 檔案
    environment:
      COCKROACH_DATABASE: ${DATABASE_NAME}
      COCKROACH_USER: ${USER_NAME}
      COCKROACH_PASSWORD: ${PASSWORD}

    # 8080 可在網頁上開啟 db console 查詢 database 資料,
    # 26257 為 db 連線的 port
    ports:
      - "26257:26257"
      - "8080:8080"

    # 簡單宣告 docker volumes 給 cockroach 使用
    # 若有 entrypoint 腳本, 可在 docker-compose.yaml 目錄底下建立 init-scripts 目錄
    volumes:
      - roach-single:/cockroach/cockroach-data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  roach-single: