spring:
  datasource:
    url: jdbc:postgresql://localhost:26257/distrise?sslmode=disable
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 20
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
        connection:
          provider_disables_autocommit: false
    show-sql: false