spring:
  h2:
    console:
      enabled: true
      path: '/h2'
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:distrise;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE;MODE=Oracle;INIT=create schema if not exists ADP\;
    username: sa
  jpa:
    defer-datasource-initialization: true