spring:
  datasource:
    url: jdbc:postgresql://localhost:26257/distrise?sslmode=disable
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      pool-name: pol
      connection-timeout: 300
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 30000
      max-lifetime: 2000000

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDialect
        connection:
          provider_disables_autocommit: false
    show-sql: false
    hibernate:
      ddl-auto: update  # I'm lazy to create DDL schema