debug: false
server:
  port: ${SERVER_PORT:8888}
  shutdown: graceful

spring:
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: false

logging:
  level:
    root: info
    com.distrise.nostr: debug